### ISSUE TITLE
How to config pgredis?

### ISSUE THREAD

**Issue by suzixin** [yob/pgredis#52]
Hi James,
I want to test pgredis in a docker,  which required redis.conf to set some parameter to link redis from another docker.
Do you have some idea in this Scene?

thanks

**Comment by yob** [comment]
Hi @suzixin,

Before answering, I should to be clear that this was an experiment that was fun to build but I don't recommend using it in a real system anywhere.

> I want to test pgredis in a docker, which required redis.conf to set some parameter to link redis from another docker.
> Do you have some idea in this Scene?

pgredis itself can run in docker very well - it's how I intended it to be run. All configuration is via cli flags or environment variables - there's no config files.

**Comment by suzixin** [comment]
Thanks for your reply.  Things work now.

> I should to be clear that this was an experiment that was fun to build but I don't recommend using it in a real system anywhere.

pgredis is an interesting project. Apart from the fact that some redis commands are not supported, are there any flaws in it?

**Comment by yob** [comment]
The commands I've implemented are correct as far as a I know, but I assume there might be bugs. In particular, I don't know that I've tested many edge cases like passing the wrong types to commands, etc. There's a handful of known issues recorded on GitHub as well, like #50 and #51
