### ISSUE TITLE
Supporting openGauss as the backend database.

### ISSUE THREAD

**Issue by twocode** [yob/pgredis#53]
Hi @yob,
This is a very interesting project. Thanks for the creativity and efforts implementing it.
We were trying to use pgredis in one of our projects. We would pack pgredis and database all together as a Redis alternative.
We also found the project could be further improved:
1. Support more Redis commands.
2. Support the backend database dialect (openGauss, https://github.com/opengauss-mirror/openGauss-server).
3. Improve performance with redis-benchmark.

Going forward, we would probably love to improve this project in the three ways mentioned above and would like to fork a project in openGauss community. Would like to hear back from you. Thanks James.

Best

**Comment by yob** [comment]
Improved performance and support for additional commands would be nice!

I'm not familiar with openGauss - would supporting it require a database adapter layer of some kind, possibly with slightly different SQL for postgres and openGauss?

This project was a learning exercise for me. If you plan to run it in production then forking and and maintaining your own version sounds like a sensible idea to me. If you keep it open source I'll watch with interest and maybe pull some changes back here, but the MIT license also permits your fork to be private :heart:

**Comment by twocode** [comment]
Thanks for the information @yob .
>>> would supporting it require a database adapter layer of some kind, possibly with slightly different SQL for postgres and openGauss?

openGauss has a slightly different SQL from Postgres. Some commands need to be transformed to openGauss dialects. These works would be trivial.

>>> If you plan to run it in production then forking and and maintaining your own version sounds like a sensible idea to me.

Good to know. Right now we are making private changes to it internally and not making it open yet. We might will make it public or even pull some changes back to this repo in the future. But that will depend on how the project goes ;) Thanks so much for the information! ❤️
